# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# # Define a job to be invoked later in a workflow.
jobs:
    build:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - checkout
            - run: npm i
            - save_cache:
                paths:
                  - /src/node_modules
                key: npm_packages
            - run: npm run lint

    test:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm_packages
            - run: npm i
            - run: npm run test

    analyze:
        docker:
            - image: cimg/node:13.8.0
        steps:
            - checkout
            - restore_cache:
                keys:
                  - npm_packages
            - run: npm i
            - run: npm audit

# declare workflows
workflows:
    my_workflows:
        jobs:
            - build
            - test:
                requires:
                    - build
            - analyze:
                requires:
                    - test
                

                
